apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    name: master
    port: 8080
    targetPort: 8080
  - protocol: TCP
    name: agent
    port: 50000
    targetPort: 50000
  selector:
    app: jenkins-master
